import json
import os
import random
import re
import sys
import time

import numpy as np

from common_utils import strToSuffix
from params import configs


def SD2_instance_generator(config):
    """
    :param config: a package of parameters
    :return: a fjsp instance generated by SD2, with
        job_length : the number of operations in each job (shape [J])
        op_pt: the processing time matrix with shape [N, M],
                where op_pt[i,j] is the processing time of the ith operation
                on the jth machine or 0 if $O_i$ can not process on $M_j$
        op_per_mch : the average number of compatible machines of each operation
    """
    n_j = config.n_j
    n_m = config.n_m
    if config.op_per_job == 0:
        op_per_job = n_m
    else:
        op_per_job = config.op_per_job

    low = config.low
    high = config.high
    data_suffix = config.data_suffix

    op_per_mch_min = 1
    if data_suffix == "nf":
        op_per_mch_max = 1
    elif data_suffix == "mix":
        op_per_mch_max = n_m
    else:
        op_per_mch_min = config.op_per_mch_min
        op_per_mch_max = config.op_per_mch_max
    if op_per_mch_min < 1 or op_per_mch_max > n_m:
        print(
            f"Error from Instance Generation: [{op_per_mch_min},{op_per_mch_max}] "
            f"with num_mch : {n_m}"
        )
        sys.exit()

    n_op = int(n_j * op_per_job)
    job_length = np.full(shape=(n_j,), fill_value=op_per_job, dtype=int)
    op_use_mch = np.random.randint(
        low=op_per_mch_min, high=op_per_mch_max + 1, size=n_op
    )

    op_per_mch = np.mean(op_use_mch)
    op_pt = np.random.randint(low=low, high=high + 1, size=(n_op, n_m))

    for row in range(op_pt.shape[0]):
        mch_num = int(op_use_mch[row])
        if mch_num < n_m:
            inf_pos = np.random.choice(np.arange(0, n_m), n_m - mch_num, replace=False)
            op_pt[row][inf_pos] = 0

    return job_length, op_pt, op_per_mch


def matrix_to_text(job_length, op_pt, op_per_mch):
    """
        Convert matrix form of the data into test form
    :param job_length: the number of operations in each job (shape [J])
    :param op_pt: the processing time matrix with shape [N, M],
                where op_pt[i,j] is the processing time of the ith operation
                on the jth machine or 0 if $O_i$ can not process on $M_j$
    :param op_per_mch: the average number of compatible machines of each operation
    :return: the standard text form of the instance
    """
    n_j = job_length.shape[0]
    n_op, n_m = op_pt.shape
    text = [f"{n_j}\t{n_m}\t{op_per_mch}"]

    op_idx = 0
    for j in range(n_j):
        line = f"{job_length[j]}"
        for _ in range(job_length[j]):
            use_mch = np.where(op_pt[op_idx] != 0)[0]
            line = line + " " + str(use_mch.shape[0])
            for k in use_mch:
                line = line + " " + str(k + 1) + " " + str(op_pt[op_idx][k])
            op_idx += 1

        text.append(line)

    return text


def text_to_matrix(text):
    """
            Convert text form of the data into matrix form
    :param text: the standard text form of the instance
    :return:  the matrix form of the instance
            job_length: the number of operations in each job (shape [J])
            op_pt: the processing time matrix with shape [N, M],
                where op_pt[i,j] is the processing time of the ith operation
                on the jth machine or 0 if $O_i$ can not process on $M_j$
    """
    n_j = int(re.findall(r"\d+\.?\d*", text[0])[0])
    n_m = int(re.findall(r"\d+\.?\d*", text[0])[1])

    job_length = np.zeros(n_j, dtype="int32")
    op_pt = []

    for i in range(n_j):
        content = np.array([int(s) for s in re.findall(r"\d+\.?\d*", text[i + 1])])
        job_length[i] = content[0]

        idx = 1
        for j in range(content[0]):
            op_pt_row = np.zeros(n_m, dtype="int32")
            mch_num = content[idx]
            next_idx = idx + 2 * mch_num + 1
            for k in range(mch_num):
                mch_idx = content[idx + 2 * k + 1]
                pt = content[idx + 2 * k + 2]
                op_pt_row[mch_idx - 1] = pt

            idx = next_idx
            op_pt.append(op_pt_row)

    op_pt = np.array(op_pt)

    return job_length, op_pt


def load_data_from_files(directory, load_reference_points=False):
    """
        load all files within the specified directory
    :param directory: the directory of files
    :return: a list of data (matrix form) in the directory
    """
    if not os.path.exists(directory):
        return [], []

    reference_points = []
    reference_points_json = None
    if load_reference_points:
        with open("./data/reference_points.json", "r") as file:
            reference_points_json = json.load(file)

    dataset_job_length = []
    dataset_op_pt = []
    for root, dirs, files in os.walk(directory):
        # sort files by index
        files.sort(key=lambda s: int(re.findall("\d+", s)[0]))
        files.sort(key=lambda s: int(re.findall("\d+", s)[-1]))
        for f in files:
            # print(f)
            g = open(os.path.join(root, f), "r").readlines()
            job_length, op_pt = text_to_matrix(g)
            dataset_job_length.append(job_length)
            dataset_op_pt.append(op_pt)
            if load_reference_points and reference_points_json is not None:
                reference_points_list = reference_points_json[
                    "/" + "/".join(root.split("/")[2:]) + "/" + f
                ]
                # Safely extract reference points, filling missing ones with 0.0 (order matches reference_points.json layout)
                ref_row = []
                for idx in [0, 2, 7, 10, 11, 12, 9]:
                    if idx < len(reference_points_list):
                        ref_row.append(reference_points_list[idx])
                    else:
                        ref_row.append(0.0)
                reference_points.append(ref_row)
                # makespan, average_flowtime, total_tardiness (0.5),
                # total_earliness (0.5), total_earliness (0.9), total_earliness (1.0), costs
    if load_reference_points:
        return (dataset_job_length, dataset_op_pt), reference_points
    else:
        return dataset_job_length, dataset_op_pt


def pack_data_from_config(data_source, test_data, load_reference_points=False):
    """
        load multiple data (specified by the variable 'test_data')
        of the specified data source.
    :param data_source: the source of data (SD1/SD2/BenchData)
    :param test_data: the list of data's name
    :return: a list of data (matrix form) and its name
    """
    data_list = []
    reference_points_list = []
    for data_name in test_data:
        data_path = f"./data/{data_source}/{data_name}"
        if load_reference_points:
            data, reference_points = load_data_from_files(
                data_path, load_reference_points
            )
        else:
            data = load_data_from_files(data_path, load_reference_points)
            reference_points = None
        data_list.append((data, data_name))
        reference_points_list.append((reference_points, data_name))
    if load_reference_points:
        return data_list, reference_points_list
    else:
        return data_list


def generate_data_to_files(seed, directory, config):
    """
        Generate data and save it to the specified directory
    :param seed: seed for data generation
    :param directory: the directory for saving files
    :param config: other parameters related to data generation
    """
    n_j = config.n_j
    n_m = config.n_m
    source = config.data_source
    batch_size = config.data_size
    data_suffix = config.data_suffix

    suffix = strToSuffix(data_suffix)
    low = config.low
    high = config.high

    filename = "{}x{}{}".format(n_j, n_m, suffix)
    np.random.seed(seed)
    random.seed(seed)

    print("-" * 25 + "Data Setting" + "-" * 25)
    print(f"seed : {seed}")
    print(f"data size : {batch_size}")
    print(f"data source: {source}")
    print(f"filename : {filename}")
    print(f"processing time : [{low},{high}]")
    print(f"mode : {data_suffix}")
    print("-" * 50)

    path = directory + filename

    if (not os.path.exists(path)) or config.cover_data_flag:
        if not os.path.exists(path):
            os.makedirs(path)

        for idx in range(batch_size):
            if source == "SD2":
                job_length, op_pt, op_per_mch = SD2_instance_generator(config=config)

                lines_doc = matrix_to_text(job_length, op_pt, op_per_mch)

                doc = open(
                    path
                    + "/"
                    + filename
                    + "_{}.fjs".format(str.zfill(str(idx + 1), 3)),
                    "w",
                )
                for i in range(len(lines_doc)):
                    print(lines_doc[i], file=doc)
                doc.close()
            elif source == "JSSP":
                job_length, op_pt = generate_taillard_jssp_instance(n_j, n_m, low, high)

                # Calculate average machines per operation (for JSSP it's always 1)
                op_per_mch = 1.0

                lines_doc = matrix_to_text(job_length, op_pt, op_per_mch)

                doc = open(
                    path
                    + "/"
                    + filename
                    + "_{}.fjs".format(str.zfill(str(idx + 1), 3)),
                    "w",
                )
                for i in range(len(lines_doc)):
                    print(lines_doc[i], file=doc)
                doc.close()
            elif source == "FFSP":
                # For FFSP, we need stages_machines configuration
                # Default: create stages with varying machine counts
                n_stages = config.n_m if hasattr(config, "n_stages") else min(n_m, 4)
                if hasattr(config, "stages_machines"):
                    stages_machines = config.stages_machines
                else:
                    # Default: distribute machines across stages
                    base_machines = max(1, n_m // n_stages)
                    stages_machines = [base_machines] * n_stages
                    # Distribute remaining machines
                    remaining = n_m - sum(stages_machines)
                    for i in range(remaining):
                        stages_machines[i % n_stages] += 1

                job_length, op_pt = generate_ffsp_instance(
                    n_j, stages_machines, low, high
                )

                # Calculate average machines per operation (for FFSP it's average machines per stage)
                op_per_mch = np.mean(stages_machines)

                lines_doc = matrix_to_text(job_length, op_pt, op_per_mch)

                doc = open(
                    path
                    + "/"
                    + filename
                    + "_{}.fjs".format(str.zfill(str(idx + 1), 3)),
                    "w",
                )
                for i in range(len(lines_doc)):
                    print(lines_doc[i], file=doc)
                doc.close()
    else:
        print("the data already exists...")


def generate_jssp_validation_data_to_files(
    n_j, n_m, seed, directory, num_instances=50, low=1, high=99
):
    """
    Generate JSSP validation data and save it to files

    Args:
        n_j: Number of jobs
        n_m: Number of machines
        seed: Seed for data generation
        directory: Directory to save the files
        num_instances: Number of validation instances to generate
        low: Lower bound for processing times
        high: Upper bound for processing times
    """
    filename = f"{n_j}x{n_m}_jssp"
    np.random.seed(seed)
    random.seed(seed)

    print("-" * 25 + "JSSP Validation Data Generation" + "-" * 25)
    print(f"seed : {seed}")
    print(f"data size : {num_instances}")
    print("data source: JSSP")
    print(f"filename : {filename}")
    print(f"processing time : [{low},{high}]")
    print(f"jobs x machines : {n_j}x{n_m}")
    print("-" * 50)

    path = directory + filename

    if not os.path.exists(path):
        os.makedirs(path)

    for idx in range(num_instances):
        job_length, op_pt = generate_taillard_jssp_instance(n_j, n_m, low, high)

        # Calculate average machines per operation (for JSSP it's always 1)
        op_per_mch = 1.0

        lines_doc = matrix_to_text(job_length, op_pt, op_per_mch)

        doc = open(
            path + "/" + filename + "_{}.fjs".format(str.zfill(str(idx + 1), 3)),
            "w",
        )
        for i in range(len(lines_doc)):
            print(lines_doc[i], file=doc)
        doc.close()

    print(f"Successfully generated {num_instances} JSSP validation instances in {path}")


class CaseGenerator:
    """

    the generator of SD1 data (imported from "songwenas12/fjsp-drl"),
    used for generating training instances

    Remark: the validation and testing intances of SD1 data are
    imported from "songwenas12/fjsp-drl"
    """

    def __init__(
        self,
        job_init,
        num_mas,
        opes_per_job_min,
        opes_per_job_max,
        nums_ope=None,
        path="./  ",
        flag_same_opes=True,
        flag_doc=False,
    ):
        # n_i
        self.str_time = time.strftime("%Y%m%d_%H%M%S", time.localtime(time.time()))
        if nums_ope is None:
            nums_ope = []
        self.flag_doc = flag_doc  # Whether save the instance to a file
        self.flag_same_opes = flag_same_opes
        self.nums_ope = nums_ope
        self.path = path  # Instance save path (relative path)
        self.job_init = job_init
        self.num_mas = num_mas

        self.mas_per_ope_min = (
            1  # The minimum number of machines that can process an operation
        )
        self.mas_per_ope_max = num_mas

        self.opes_per_job_min = (
            opes_per_job_min  # The minimum number of operations for a job
        )
        self.opes_per_job_max = opes_per_job_max

        self.proctime_per_ope_min = 1  # Minimum average processing time
        self.proctime_per_ope_max = 20

        self.proctime_dev = 0.2

    def get_case(self, idx=0):
        """
        Generate FJSP instance
        :param idx: The instance number
        """
        self.num_jobs = self.job_init
        if not self.flag_same_opes:
            self.nums_ope = [
                random.randint(self.opes_per_job_min, self.opes_per_job_max)
                for _ in range(self.num_jobs)
            ]
        self.num_opes = sum(self.nums_ope)
        self.nums_option = [
            random.randint(self.mas_per_ope_min, self.mas_per_ope_max)
            for _ in range(self.num_opes)
        ]
        self.num_options = sum(self.nums_option)

        self.ope_ma = []
        for val in self.nums_option:
            self.ope_ma = self.ope_ma + sorted(
                random.sample(range(1, self.num_mas + 1), val)
            )
        self.proc_time = []

        self.proc_times_mean = [
            random.randint(self.proctime_per_ope_min, self.proctime_per_ope_max)
            for _ in range(self.num_opes)
        ]
        for i in range(len(self.nums_option)):
            low_bound = max(
                self.proctime_per_ope_min,
                round(self.proc_times_mean[i] * (1 - self.proctime_dev)),
            )
            high_bound = min(
                self.proctime_per_ope_max,
                round(self.proc_times_mean[i] * (1 + self.proctime_dev)),
            )
            proc_time_ope = [
                random.randint(low_bound, high_bound)
                for _ in range(self.nums_option[i])
            ]
            self.proc_time = self.proc_time + proc_time_ope

        self.num_ope_biass = [sum(self.nums_ope[0:i]) for i in range(self.num_jobs)]
        self.num_ma_biass = [sum(self.nums_option[0:i]) for i in range(self.num_opes)]
        line0 = "{0}\t{1}\t{2}\n".format(
            self.num_jobs, self.num_mas, self.num_options / self.num_opes
        )
        lines_doc = []
        lines_doc.append(
            "{0}\t{1}\t{2}".format(
                self.num_jobs, self.num_mas, self.num_options / self.num_opes
            )
        )
        for i in range(self.num_jobs):
            flag = 0
            flag_time = 0
            flag_new_ope = 1
            idx_ope = -1
            idx_ma = 0
            line = []
            option_max = sum(
                self.nums_option[
                    self.num_ope_biass[i] : (self.num_ope_biass[i] + self.nums_ope[i])
                ]
            )
            idx_option = 0
            while True:
                if flag == 0:
                    line.append(self.nums_ope[i])
                    flag += 1
                elif flag == flag_new_ope:
                    idx_ope += 1
                    idx_ma = 0
                    flag_new_ope += (
                        self.nums_option[self.num_ope_biass[i] + idx_ope] * 2 + 1
                    )
                    line.append(self.nums_option[self.num_ope_biass[i] + idx_ope])
                    flag += 1
                elif flag_time == 0:
                    line.append(
                        self.ope_ma[
                            self.num_ma_biass[self.num_ope_biass[i] + idx_ope] + idx_ma
                        ]
                    )
                    flag += 1
                    flag_time = 1
                else:
                    line.append(
                        self.proc_time[
                            self.num_ma_biass[self.num_ope_biass[i] + idx_ope] + idx_ma
                        ]
                    )
                    flag += 1
                    flag_time = 0
                    idx_option += 1
                    idx_ma += 1
                if idx_option == option_max:
                    str_line = " ".join([str(val) for val in line])
                    lines_doc.append(str_line)
                    break
        job_length, op_pt = text_to_matrix(lines_doc)
        if self.flag_doc:
            if not os.path.exists(self.path):
                os.makedirs(self.path)
            # doc = open(
            #     self.path + '/' + '{0}x{1}_{2}.fjs'.format(self.num_jobs, self.num_mas, str.zfill(str(idx + 1), 3)),
            #     'w')
            doc = open(self.path + f"/{self.str_time}.txt", "a")
            # doc = open(self.path + f'/ours.txt', 'a')
            for i in range(len(lines_doc)):
                print(lines_doc[i], file=doc)
            doc.close()

        return job_length, op_pt, self.num_options / self.num_opes


def main():
    if configs.data_type == "test":
        if configs.data_source == "JSSP":
            # For JSSP test data generation
            generate_jssp_validation_data_to_files(
                configs.n_j,
                configs.n_m,
                configs.seed_datagen,
                f"./data/{configs.data_source}/",
                num_instances=configs.data_size,
                low=configs.low,
                high=configs.high,
            )
        elif configs.data_source == "FFSP":
            # For FFSP test data generation
            n_stages = getattr(configs, "n_stages", min(configs.n_m, 4))
            if hasattr(configs, "stages_machines"):
                stages_machines = configs.stages_machines
            else:
                # Default: distribute machines across stages
                base_machines = max(1, configs.n_m // n_stages)
                stages_machines = [base_machines] * n_stages
                # Distribute remaining machines
                remaining = configs.n_m - sum(stages_machines)
                for i in range(remaining):
                    stages_machines[i % n_stages] += 1

            generate_ffsp_validation_data_to_files(
                configs.n_j,
                stages_machines,
                configs.seed_datagen,
                f"./data/{configs.data_source}/",
                num_instances=configs.data_size,
                low=configs.low,
                high=configs.high,
            )
        else:
            generate_data_to_files(
                configs.seed_datagen, f"./data/{configs.data_source}/", configs
            )
    elif configs.data_type == "vali":
        if configs.data_source == "JSSP":
            # For JSSP validation data generation
            generate_jssp_validation_data_to_files(
                configs.n_j,
                configs.n_m,
                configs.seed_train_vali_datagen,
                f"./data/data_train_vali/{configs.data_source}/",
                num_instances=configs.data_size,  # Use configs.data_size instead of hardcoded 50
                low=configs.low,
                high=configs.high,
            )
        elif configs.data_source == "FFSP":
            # For FFSP validation data generation
            n_stages = getattr(configs, "n_stages", min(configs.n_m, 4))
            if hasattr(configs, "stages_machines"):
                stages_machines = configs.stages_machines
            else:
                # Default: distribute machines across stages
                base_machines = max(1, configs.n_m // n_stages)
                stages_machines = [base_machines] * n_stages
                # Distribute remaining machines
                remaining = configs.n_m - sum(stages_machines)
                for i in range(remaining):
                    stages_machines[i % n_stages] += 1

            generate_ffsp_validation_data_to_files(
                configs.n_j,
                stages_machines,
                configs.seed_train_vali_datagen,
                f"./data/data_train_vali/{configs.data_source}/",
                num_instances=configs.data_size,
                low=configs.low,
                high=configs.high,
            )
        else:
            # generate validation instances for SD1/SD2
            generate_data_to_files(
                configs.seed_train_vali_datagen,
                f"./data/data_train_vali/{configs.data_source}/",
                configs,
            )
    else:
        print(
            f"Error from Instance Generation: incorrect data type {configs.data_type}"
        )
        sys.exit()


def generate_taillard_jssp_instance(n_j, n_m, low=1, high=99):
    """
    Generate a Job Shop Scheduling Problem (JSSP) instance using the Taillard method.
    In JSSP, each operation can only be performed on exactly one machine.

    Args:
        n_j: Number of jobs
        n_m: Number of machines
        low: Lower bound for processing times
        high: Upper bound for processing times

    Returns:
        job_length: Array of number of operations per job (shape: [n_j])
        op_pt: Processing time matrix (shape: [n_op, n_m]) where n_op = n_j * n_m
    """
    # For JSSP, each job has exactly n_m operations (one for each machine)
    job_length = np.full(n_j, n_m, dtype=np.int32)

    # Total number of operations
    n_op = n_j * n_m

    # Initialize the operation processing time matrix (2D format expected by matrix_to_text)
    op_pt = np.zeros((n_op, n_m), dtype=np.int32)

    # Generate processing times from uniform distribution [low, high]
    processing_times = np.random.randint(low, high + 1, size=(n_j, n_m))

    # For each job, create a random permutation of machines
    op_idx = 0
    for job in range(n_j):
        # Generate a random permutation of machines for this job
        machine_sequence = np.random.permutation(n_m)

        # Assign each operation to its designated machine
        for op_in_job, machine_id in enumerate(machine_sequence):
            # Set processing time for this operation on its assigned machine
            op_pt[op_idx, machine_id] = processing_times[job, op_in_job]
            # All other machines have processing time 0 (indicating unavailable)
            op_idx += 1

    return job_length, op_pt


def generate_ffsp_instance(n_j, stages_machines, low=1, high=99):
    """
    Generate a Flexible Flow Shop Scheduling Problem (FFSP) instance.
    In FFSP, jobs flow through sequential stages, with multiple machines per stage.

    Args:
        n_j: Number of jobs
        stages_machines: List of number of machines per stage [m1, m2, ..., mS]
        low: Lower bound for processing times
        high: Upper bound for processing times

    Returns:
        job_length: Array of number of operations per job (shape: [n_j])
        op_pt: Processing time matrix (shape: [n_op, total_machines]) where n_op = n_j * n_stages
    """
    n_stages = len(stages_machines)
    total_machines = sum(stages_machines)

    # For FFSP, each job has exactly n_stages operations (one per stage)
    job_length = np.full(n_j, n_stages, dtype=np.int32)

    # Total number of operations
    n_op = n_j * n_stages

    # Initialize the operation processing time matrix (2D format expected by matrix_to_text)
    op_pt = np.zeros((n_op, total_machines), dtype=np.int32)

    # Generate processing times from uniform distribution [low, high]
    op_idx = 0
    machine_offset = 0

    for job in range(n_j):
        machine_offset = 0  # Reset for each job

        for stage in range(n_stages):
            # Number of machines in this stage
            machines_in_stage = stages_machines[stage]

            # Generate processing times for this operation on all machines in this stage
            stage_processing_times = np.random.randint(
                low, high + 1, size=machines_in_stage
            )

            # Set processing times for this operation on machines in this stage
            for machine_in_stage in range(machines_in_stage):
                op_pt[op_idx, machine_offset + machine_in_stage] = (
                    stage_processing_times[machine_in_stage]
                )

            # All other machines (from other stages) have processing time 0
            op_idx += 1
            machine_offset += machines_in_stage

    return job_length, op_pt


def generate_ffsp_validation_data_to_files(
    n_j, stages_machines, seed, directory, num_instances=50, low=1, high=99
):
    """
    Generate FFSP validation data and save it to files

    Args:
        n_j: Number of jobs
        stages_machines: List of number of machines per stage
        seed: Seed for data generation
        directory: Directory to save the files
        num_instances: Number of validation instances to generate
        low: Lower bound for processing times
        high: Upper bound for processing times
    """
    n_stages = len(stages_machines)
    total_machines = sum(stages_machines)
    stages_str = "_".join(map(str, stages_machines))
    filename = f"{n_j}x{n_stages}stages_{stages_str}m_ffsp"

    np.random.seed(seed)
    random.seed(seed)

    print("-" * 25 + "FFSP Validation Data Generation" + "-" * 25)
    print(f"seed : {seed}")
    print(f"data size : {num_instances}")
    print("data source: FFSP")
    print(f"filename : {filename}")
    print(f"processing time : [{low},{high}]")
    print(f"jobs x stages : {n_j}x{n_stages}")
    print(f"machines per stage : {stages_machines}")
    print(f"total machines : {total_machines}")
    print("-" * 50)

    path = directory + filename

    if not os.path.exists(path):
        os.makedirs(path)

    for idx in range(num_instances):
        job_length, op_pt = generate_ffsp_instance(n_j, stages_machines, low, high)

        # Calculate average machines per operation (for FFSP it's the average of machines per stage)
        op_per_mch = np.mean(stages_machines)

        lines_doc = matrix_to_text(job_length, op_pt, op_per_mch)

        doc = open(
            path + "/" + filename + "_{}.fjs".format(str.zfill(str(idx + 1), 3)),
            "w",
        )
        for i in range(len(lines_doc)):
            print(lines_doc[i], file=doc)
        doc.close()

    print(f"Successfully generated {num_instances} FFSP validation instances in {path}")


if __name__ == "__main__":
    main()
    print("success!")
